version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: car_rental_database_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: car_rental_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  car-rental:
    build: ./
    container_name: car-rental-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql_data: