version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: car_location_database_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: car_location_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  car-location-server:
    build: ./server
    container_name: car-location-server-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: