package com.coding.app.models.enums;

public enum Brand {

	RENAULT, PEUGEOT, CITROEN, BMW, VOLKSWAGEN, ABARTH, ABI, AC, ACREA, ADLER, ADRIA, AIWAYS, AIXAM, ALEKO, ALKE,
	ALPINA, ALPINE, ALVIS, AMC, AMPHICAR, ANAIG, APAL, ARIEL, ARO, ARTEGA, ATLAS, AUBURN, AUDI, AUSTIN, AUTOBIANCHI,
	AUTOSTAR, AUVERLAND, AXXOR, BELLIER, BENTLEY, BERLIET, BERTONE, BITTER, BIZZARRINI, BOLLORE, BOOXT, BORGWARD,
	BREMACH, BRISTOL, BUGATTI, BUICK, BURSTNER, CADILLAC, CARAVELAIR, CARBODIES, CARDINAL, CARRIAGE, CARVER, CASALINI,
	CASITA, CATERHAM, CG, CHATENET, CHEVROLET, CHRYSLER, CLEMENSON, CLENET, CONSTRUCTAM, COSTE, COURB, CUPRA,
	DACIA, DAEWOO, DAF, DAIHATSU, DAIMLER, DALLARA, DANGEL, DARMONT, DATSUN, DELAGE, DELAHAYE, DELTA, DETHLEFFS,
	DEVINCI, DIGUE, DKW, DODGE, DONKERVOORT, DONNET, DS, DUE, EAGLE, EBRO, EDSEL, ELDDIS, ELV, EMBUGGY, ERAD, ERIBA,
	ESTEREL, ESTRIMA, EUROSTAR, EXCALIBUR, FENDT, FERRARI, FIAT, FISKER, FLEURETTE, FORD, FORNASARI, FSO, GILLET,
	GINETTA, GLAS, GMC, GME, GOUPIL, GRANDIN, GRECAV, GRUAU, GUMPERT, HALMARQ, HILLMAN, HOBBY, HOMMELL, HONDA,
	HOTCHKISS, HUDSON, HUMBER, HUMMER, HYUNDAI, IMPERIAL, INEOS, INFINITI, INNOCENTI, INTERMECCANICA, INTERNATIONAL,
	ISO, ISUZU, ITALCAR, IVECO, JAGUAR, JEEP, JENSEN, JIAYUAN, KARMA, KEYSTONE, KIA, KIP, KNAUS, KOENIGSEGG, KTM, LADA,
	LAGONDA, LAMBORGHINI, LANCIA, LAND_ROVER, LANDWIND, LANTANA, LARAKI, LDV, LEFEUNE, LEVC, LEXUS, LIGIER, LINCOLN, LMC, LORD,
	LOTUS, MAHINDRA, MAN, MARCADIER, MARCOS, MARTIN, MARUTI, MASERATI, MATRA, MAYBACH, MAZDA, MCLAREN, MEGA, MERCEDES,
	MERCURY, MESSERSCHMITT, MEV, MG, MICROCAR, MINAUTO, MINI, MITSUBISHI, MITSUOKA, MOBILIS, MONTANA, MONTEVERDI,
	MORGAN, MORRIS, MVS, NASH, NECKAR, NEWMAR, NEWYARK, NISSAN, NOBLE, NOSMOKE, NSU, OLDSMOBILE, OPEL, OSI, PACKARD,
	PAGANI, PANHARD, PANTHER, PEGASO, PGO, PIAGGIO, PLUMA, PLYMOUTH, POLESTAR, POLSKI, PONTIAC, PORSCHE,
	PROTON, QOROS, RACLET, RADICAL, RAM, RAPIDO, RAULT, REALM, RELIANT, RILEY, RIVIAN, ROSENGART, ROVER, SAAB, SAIC,
	SALEEN, SALMSON, SANTANA, SAURIUM, SAVEL, SAVIEM, SCANIA, SCION, SEAT, SECMA, SERES, SHELBY, SIMCA, SINGER, SKODA, SMART,
	SMS, SOVAMAG, SPECTRE, SPYKER, SSANGYONG, STAR, STERCKEMAN, STUDEBAKER, STUTZ, SUBARU, SUNBEAM, SUZUKI, TABBERT,
	TALBOT, TATA, TEILHOL, TESLA, THINK, TISCHER, TOYOTA, TRABANT, TRAVEL, TRIGANO, TRIUMPH, TVR, ULTIMA, UMM, VAUXHALL,
	VELAM, VENTURI, VESPA, VINFAST, VOLTEIS, VOLVO, WEIPPERT, WESTFIELD, WIESMANN, WILK, WILLERBY, WILLYS,
	WOLSELEY, XINYANG, ZASTAVA, ALFA_ROMEO, ACURA, GENESIS, LUCID;
}
